# Generated by Django 5.0.6 on 2024-06-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=599, verbose_name='Орган выдачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'орган',
                'verbose_name_plural': 'Орган выдачи',
            },
        ),
        migrations.CreateModel(
            name='QuantitySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=599, verbose_name='Форма обучения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'форму',
                'verbose_name_plural': 'Форма обучения',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=599, verbose_name='Наименование региона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='StatusLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=199, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='DBLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_register', models.CharField(blank=True, max_length=599, unique=True, verbose_name='Номер регистрации')),
                ('name_entity', models.CharField(blank=True, max_length=599, verbose_name='Наименование юр лиц')),
                ('tax_name', models.CharField(blank=True, max_length=599, verbose_name='Идентификационный номер')),
                ('entity_address', models.CharField(blank=True, max_length=599, verbose_name='Юридический адрес')),
                ('address_program', models.CharField(blank=True, max_length=599, verbose_name='Адрес реализационной прг')),
                ('cipher', models.CharField(blank=True, max_length=599, verbose_name='Шифр')),
                ('title_school', models.CharField(blank=True, max_length=599, verbose_name='Наименование оброзовательной учр')),
                ('quantity_school', models.CharField(blank=True, max_length=599, verbose_name='Кол. обучающих')),
                ('issuing_license', models.CharField(blank=True, max_length=599, verbose_name='Основание выдачи')),
                ('data_license', models.DateTimeField(verbose_name='Дата выдачи')),
                ('form_number', models.CharField(blank=True, max_length=599, verbose_name='Номер и серия бланка')),
                ('form_number_suspended', models.CharField(blank=True, max_length=599, verbose_name='Основание срок приостанавления')),
                ('form_number_start', models.CharField(blank=True, max_length=599, verbose_name='Основание дата возобновления')),
                ('form_number_stop', models.CharField(blank=True, max_length=599, verbose_name='Основание дата прекращения')),
                ('data_address', models.CharField(blank=True, max_length=599, verbose_name='Данные о смене адреса')),
                ('form_number_data', models.CharField(blank=True, max_length=599, verbose_name='Основание дата выдачи дубликата')),
                ('file', models.FileField(blank=True, upload_to='file/', verbose_name='Вставка файла')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('issuing_authorities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.issuingauthority', verbose_name='Орган выдачи')),
                ('quantities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.quantityschool', verbose_name='Форма обучения')),
                ('regions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.region', verbose_name='Регион')),
                ('code_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.statuslicense', verbose_name='Статус выдачи')),
            ],
            options={
                'verbose_name': 'лицензию',
                'verbose_name_plural': 'База лицензии',
            },
        ),
    ]
