# Generated by Django 5.0.6 on 2024-05-28 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=599, verbose_name='Орган выдачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'орган',
                'verbose_name_plural': 'Орган выдачи',
            },
        ),
        migrations.RemoveField(
            model_name='dblicense',
            name='issuing_authority',
        ),
        migrations.AddField(
            model_name='dblicense',
            name='issuing_authorities',
            field=models.ForeignKey(default=121, on_delete=django.db.models.deletion.CASCADE, to='license.issuingauthority', verbose_name='Орган выдачи'),
            preserve_default=False,
        ),
    ]
