# Generated by Django 5.0.6 on 2024-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_issuingauthority_remove_dblicense_issuing_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblicense',
            name='status',
            field=models.CharField(choices=[('issued', 'Выдан'), ('suspended', 'Приостановлен'), ('revoked', 'Аннулирован')], default='issued', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='dblicense',
            name='number_register',
            field=models.CharField(blank=True, max_length=599, unique=True, verbose_name='Номер регистрации'),
        ),
    ]
