# Generated by Django 5.0.6 on 2024-06-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_rename_statuslicense_codelicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblicense',
            name='term',
            field=models.CharField(blank=True, max_length=599, verbose_name='Срок действия'),
        ),
    ]
