# Generated by Django 5.0.6 on 2024-06-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_alter_dblicense_data_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblicense',
            name='additional_titles',
            field=models.JSONField(default=list),
        ),
    ]
