# Generated by Django 5.0.6 on 2024-06-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_dblicense_additional_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dblicense',
            name='additional_titles',
        ),
    ]
