# Generated by Django 5.0.6 on 2024-06-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_remove_dblicense_additional_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dblicense',
            name='quantities',
            field=models.CharField(blank=True, max_length=599, verbose_name='Форма обучения'),
        ),
        migrations.DeleteModel(
            name='QuantitySchool',
        ),
    ]
