# Generated by Django 5.0.6 on 2024-06-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_alter_dblicense_quantities_delete_quantityschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dblicense',
            name='quantities',
            field=models.JSONField(blank=True, max_length=599, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='dblicense',
            name='quantity_school',
            field=models.JSONField(blank=True, max_length=599, verbose_name='Кол. обучающих'),
        ),
        migrations.AlterField(
            model_name='dblicense',
            name='title_school',
            field=models.JSONField(blank=True, max_length=599, verbose_name='Наименование оброзовательной учр'),
        ),
    ]
