# Generated by Django 5.0.6 on 2024-06-07 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_alter_dblicense_quantities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_school', models.CharField(blank=True, max_length=599, verbose_name='Наименование оброзовательной учр')),
                ('quantity_school', models.CharField(blank=True, max_length=599, verbose_name='Кол. обучающих')),
                ('quantities', models.CharField(blank=True, max_length=599, verbose_name='Форма обучения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Форма для разрешения',
                'verbose_name_plural': 'Форма для разрешение',
            },
        ),
        migrations.RemoveField(
            model_name='dblicense',
            name='quantities',
        ),
        migrations.RemoveField(
            model_name='dblicense',
            name='quantity_school',
        ),
        migrations.RemoveField(
            model_name='dblicense',
            name='title_school',
        ),
        migrations.AddField(
            model_name='dblicense',
            name='form_add',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='license.formadd', verbose_name='Форма для зап. органа'),
            preserve_default=False,
        ),
    ]
