# Generated by Django 5.0.6 on 2024-06-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0009_formadd_remove_dblicense_quantities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dblicense',
            name='form_add',
        ),
        migrations.AddField(
            model_name='dblicense',
            name='form_add',
            field=models.ManyToManyField(related_name='entities', to='license.formadd', verbose_name='Форма для зап. органа'),
        ),
    ]
