# Generated by Django 5.0.6 on 2024-06-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_remove_dblicense_form_add_dblicense_form_add'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dblicense',
            options={'verbose_name': 'лицензию', 'verbose_name_plural': 'База лицензий'},
        ),
        migrations.AlterModelOptions(
            name='formadd',
            options={'verbose_name': 'Форма для разрешения', 'verbose_name_plural': 'Форма для разрешений'},
        ),
        migrations.AlterField(
            model_name='dblicense',
            name='address_program',
            field=models.CharField(blank=True, max_length=599, verbose_name='Адрес реализационной программы'),
        ),
        migrations.AlterField(
            model_name='dblicense',
            name='form_number_suspended',
            field=models.CharField(blank=True, max_length=2099, verbose_name='Основание срок приостановления'),
        ),
        migrations.AlterField(
            model_name='dblicense',
            name='name_entity',
            field=models.CharField(blank=True, max_length=599, verbose_name='Наименование юр. лица'),
        ),
        migrations.AlterField(
            model_name='formadd',
            name='quantity_school',
            field=models.CharField(blank=True, max_length=599, verbose_name='Кол. обучающихся'),
        ),
        migrations.AlterField(
            model_name='formadd',
            name='title_school',
            field=models.CharField(blank=True, max_length=599, verbose_name='Наименование образовательного учреждения'),
        ),
    ]
