# Generated by Django 5.0.6 on 2024-06-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0011_alter_dblicense_options_alter_formadd_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dblicense',
            name='form_add',
        ),
        migrations.AddField(
            model_name='dblicense',
            name='quantities',
            field=models.CharField(blank=True, max_length=599, verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='dblicense',
            name='quantity_school',
            field=models.CharField(blank=True, max_length=599, verbose_name='Кол. обучающихся'),
        ),
        migrations.AddField(
            model_name='dblicense',
            name='title_school',
            field=models.CharField(blank=True, max_length=599, verbose_name='Наименование образовательного учреждения'),
        ),
        migrations.DeleteModel(
            name='FormAdd',
        ),
    ]
